'use strict';
/**
 * LDBWSOperation.ts
 * This defines the available LDBWS Operation Requests. 
 * See https://lite.realtime.nationalrail.co.uk/OpenLDBWS/ for more details.
 */
import { EOperation, EStaffOperation } from "./interfaces";

const Operation = {
   GET_DEPARTURE_BOARD: EOperation.GET_DEPARTURE_BOARD,
   GET_DEPARTURE_BOARD_WITH_DETAILS: EOperation.GET_DEPARTURE_BOARD_WITH_DETAILS,
   GET_ARRIVAL_BOARD: EOperation.GET_ARRIVAL_BOARD,
   GET_ARRIVAL_BOARD_WITH_DETAILS: EOperation.GET_ARRIVAL_BOARD_WITH_DETAILS,
   GET_ARRIVAL_DEPARTURE_BOARD: EOperation.GET_ARRIVAL_DEPARTURE_BOARD,
   GET_ARRIVAL_DEPARTURE_BOARD_WITH_DETAILS: EOperation.GET_ARRIVAL_DEPARTURE_BOARD_WITH_DETAILS,
   GET_NEXT_DEPARTURES: EOperation.GET_NEXT_DEPARTURES,
   GET_NEXT_DEPARTURES_WITH_DETAILS: EOperation.GET_NEXT_DEPARTURES_WITH_DETAILS,
   GET_FASTEST_DEPARTURES: EOperation.GET_FASTEST_DEPARTURES,
   GET_FASTEST_DEPARTURES_WITH_DETAILS: EOperation.GET_FASTEST_DEPARTURES_WITH_DETAILS,
   GET_SERVICE_DETAILS: EOperation.GET_SERVICE_DETAILS
 }

export default Operation;

 const StaffOperation = {
  GET_DEPARTURE_BOARD: EOperation.GET_DEPARTURE_BOARD,
  GET_DEPARTURE_BOARD_WITH_DETAILS: EOperation.GET_DEPARTURE_BOARD_WITH_DETAILS,
  GET_ARRIVAL_BOARD: EOperation.GET_ARRIVAL_BOARD,
  GET_ARRIVAL_BOARD_WITH_DETAILS: EOperation.GET_ARRIVAL_BOARD_WITH_DETAILS,
  GET_ARRIVAL_DEPARTURE_BOARD: EOperation.GET_ARRIVAL_DEPARTURE_BOARD,
  GET_ARRIVAL_DEPARTURE_BOARD_WITH_DETAILS: EOperation.GET_ARRIVAL_DEPARTURE_BOARD_WITH_DETAILS,
  GET_NEXT_DEPARTURES: EOperation.GET_NEXT_DEPARTURES,
  GET_NEXT_DEPARTURES_WITH_DETAILS: EOperation.GET_NEXT_DEPARTURES_WITH_DETAILS,
  GET_FASTEST_DEPARTURES: EOperation.GET_FASTEST_DEPARTURES,
  GET_FASTEST_DEPARTURES_WITH_DETAILS: EOperation.GET_FASTEST_DEPARTURES_WITH_DETAILS,
  GET_SERVICE_DETAILS: EOperation.GET_SERVICE_DETAILS,

  GET_ARR_BOARD_WITH_DETAILS:                EStaffOperation.GET_ARR_BOARD_WITH_DETAILS,
  GET_ARR_DEP_BOARD_WITH_DETAILS:            EStaffOperation.GET_ARR_DEP_BOARD_WITH_DETAILS,
  GET_ARRIVAL_DEPARTURE_BOARD_BY_CRS:        EStaffOperation.GET_ARRIVAL_DEPARTURE_BOARD_BY_CRS,
  GET_ARRIVAL_DEPARTURE_BOARD_BY_TIPLOC:     EStaffOperation.GET_ARRIVAL_DEPARTURE_BOARD_BY_TIPLOC,
  GET_ARRIVAL_BOARD_BY_CRS:                  EStaffOperation.GET_ARRIVAL_BOARD_BY_CRS,
  GET_ARRIVAL_BOARD_BY_TIPLOC:               EStaffOperation.GET_ARRIVAL_BOARD_BY_TIPLOC,
  GET_DEPARTURE_BOARD_BY_CRS:                EStaffOperation.GET_DEPARTURE_BOARD_BY_CRS,
  GET_DEPARTURE_BOARD_BY_TIPLOC:             EStaffOperation.GET_DEPARTURE_BOARD_BY_TIPLOC,
  GET_DEP_BOARD_WITH_DETAILS:                EStaffOperation.GET_DEP_BOARD_WITH_DETAILS,
  GET_DISRUPTION_LIST:                       EStaffOperation.GET_DISRUPTION_LIST,
  GET_HISTORIC_DEPARTURE_BOARD:              EStaffOperation.GET_HISTORIC_DEPARTURE_BOARD,
  GET_HISTORIC_SERVICE_DETAILS:              EStaffOperation.GET_HISTORIC_SERVICE_DETAILS,
  GET_HISTORIC_TIME_LINE:                    EStaffOperation.GET_HISTORIC_TIME_LINE,
  GET_SERVICE_DETAILS_BY_RID:                EStaffOperation.GET_SERVICE_DETAILS_BY_RID,
  QUERY_HISTORIC_SERVICES:                   EStaffOperation.QUERY_HISTORIC_SERVICES,
  QUERY_SERVICES:                            EStaffOperation.QUERY_SERVICES,
 }

 export {
   StaffOperation
 };

//  module.exports.StaffOperation = StaffOperation;